version: '3'
services:
  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - app-volume:/app
      - results-volume:/app/RESULTS_FOLDER
      - upload-volume:/app/UPLOAD_FOLDER

volumes:
  app-volume:
  results-volume:
  upload-volume:
